export const sdgIconMap: Record<string, string> = {
  "Goal 1": "E-WEB-Goal-01.png",
  "Goal 2": "E-WEB-Goal-02.png",
  "Goal 3": "E-WEB-Goal-03.png",
  "Goal 4": "E-WEB-Goal-04.png",
  "Goal 5": "E-WEB-Goal-05.png",
  "Goal 6": "E-WEB-Goal-06.png",
  "Goal 7": "E-WEB-Goal-07.png",
  "Goal 8": "E-WEB-Goal-08.png",
  "Goal 9": "E-WEB-Goal-09.png",
  "Goal 10": "E-WEB-Goal-10.png",
  "Goal 11": "E-WEB-Goal-11.png",
  "Goal 12": "E-WEB-Goal-12.png",
  "Goal 13": "E-WEB-Goal-13.png",
  "Goal 14": "E-WEB-Goal-14.png",
  "Goal 15": "E-WEB-Goal-15.png",
  "Goal 16": "E-WEB-Goal-16.png",
  "Goal 17": "E-WEB-Goal-17.png",
};